Refactor for allowing conversations page widget tests
adventuresin/chat_app pull request #180
Opened 2020-06-21 06:17 UTC by tourdownunder

Thanks @nickmeinhold for your pair programming on Wed and Sat.

Inspired by a few null exceptions when using the app I created tests and made the code a bit more robust as not to cause those exceptions in the first place.

2020-06-21 08:03 UTC, nickmeinhold requested changes
Looks good mate! 

I think we should add some documentation in places where it's not obvious what the purpose of the code is, happy to help out if you want to suggest parts for me to document.

Just as a general point I think we should try and break things up as much as possible - when we have a PR like this that wanders over different aspects of the project, we should break out any parts that can be split up into separate PRs then merge dev back in with the changes. I get that it might feel like it's slowing  us down but I think the overall benefits are well worth it. By the way the suggestion is aimed at me as much as anyone else. 

Let me know if you want me to just approve and push through rather than make further changes, if so I'll add issues and then approve.  Thanks!

2020-06-21 08:03 UTC, nickmeinhold commented on lib/conversations_page.dart
> +  String _combine(List<String> displayNames) {
nice change - fixed the bug and less code, I don't think we need a separate function here now, no reason not to call join directly afaict

2020-06-21 08:03 UTC, nickmeinhold commented on lib/conversations_page.dart
> +  String _combine(List<String> displayNames) {
actually while we're discussing this, presumably we will want to change from a simple `join` to a truncated version, something like take the first 15 characters of the joined list and add '...' - I was thinking put a function in the ConversationItem class, then it'll be easy to compare in the tests. we might as well do it now I reckon, there's no added complexity or anything

2020-06-21 08:03 UTC, nickmeinhold commented on test/mocks/document_snapshot_mocks.dart
> +class FakeUserItemDocumentSnapshot implements DocumentSnapshot {
I don't understand why we need the separate classes -it's not that I think we definitely don't, I just don't understand what each class is doing (`FakeUserItemDocumentSnapshot` and `FakeMessageDocumentSnapshot` I mean). I'll go through the tests and see if I can figure it out. some documentation or a chat over zoom or meet might help

2020-06-21 08:03 UTC, nickmeinhold commented on test/unit/extensions/document_snapshot_extension_test.dart
> +  group('toUserItem()', () {
the tests will print "|group name| |test name|" so in this case it will print "toUserItem()toUserItem will have empty displayName and photoURL if not populated". I'm guessing you want DocumentSnapshot for the group name?

2020-06-21 08:03 UTC, nickmeinhold commented on test/mocks/database_mocks.dart
> +                'https://lh3.googleusercontent.com/a-/AOh14GgcLuTiYf_wdIIMAw5CPaBDQowtVTHczbRV8eZrIQ=s96-c')
do you want this taken out? I saw a commit that I assumed was you wanting to remove real URLs?

2020-06-21 08:25 UTC, tourdownunder commented
> we should break out any parts that can be split up into separate PRs then merge dev back in with the changes.

I agree it is desirable to keep them small and focused.

2020-06-21 08:39 UTC, tourdownunder commented on lib/conversations_page.dart
> +  String _combine(List<String> displayNames) {
> change from a simple `join` to a truncated version, something like take the first 15 characters of the joined list and add '...'

nice UX.

2020-06-21 08:49 UTC, tourdownunder commented on test/mocks/document_snapshot_mocks.dart
> +class FakeUserItemDocumentSnapshot implements DocumentSnapshot {
It just allows us to be explicit and have their respective constructors to have their minimum values. Though with named constructors we can just go back to 1 class.

2020-06-21 09:01 UTC, tourdownunder commented on test/mocks/document_snapshot_mocks.dart
> +class FakeUserItemDocumentSnapshot implements DocumentSnapshot {
Done just committed to use a named constructor asMessage() and asUserItem() to be able.

2020-06-21 19:32 UTC, tourdownunder commented on test/unit/extensions/document_snapshot_extension_test.dart
> +  group('toUserItem()', () {
I see toUserItem and toMessage is now the respective group names and are now not mentioned in the verbose test name.

2020-06-22 00:59 UTC, nickmeinhold commented on test/unit/extensions/document_snapshot_extension_test.dart
> +  group('toUserItem()', () {
I don't understand what you're saying

2020-06-22 01:04 UTC, nickmeinhold commented on test/unit/extensions/document_snapshot_extension_test.dart
> +  group('toUserItem()', () {
You can see examples of using the group name in combination with the test name in https://pub.dev/packages/test 
Are you saying you don't want to use the class name for the group name? Could you explain why?

2020-06-22 01:43 UTC, nickmeinhold commented on test/unit/extensions/document_snapshot_extension_test.dart
> +  group('toUserItem()', () {
Oh hang on... did this change? I'm confused.  

So to break this down, imo there were two things worth addressing:
1. the group_name|test_name combination was repeating the function name 
2. the  test output doesn't mention the class 

Unless I'm going crazy, (1) was in a previous commit but has been addressed.  

In regards to (2), I think it's worth discussing as identifying the class in the test output could be helpful in tracking things down. I don't think it's a big deal but unless there's a reason not to do it I think we should.

2020-06-22 21:01 UTC, tourdownunder commented on test/unit/extensions/document_snapshot_extension_test.dart
> +  group('toUserItem()', () {
> I don't think it's a big deal but unless there's a reason not to do it I think we should.

At first I thought the class is a dynamic data structure so I was going to group it per function instead. Though I just committed as per our regular convention to have a group per class and function name within the test. 

If I wanted to have a group for the functions could we use the class.function() like `  group('DocumentSnapshot.toMessage()' ` ?

2020-06-23 03:40 UTC, nickmeinhold commented on lib/conversations_page.dart
> +  String _combine(List<String> displayNames) {
> I was thinking put a function in the ConversationItem class, then it'll be easy to compare in the tests. we might as well do it now I reckon

do you not want to do this?  I don't mind at all but if you let me know I can add an issue - I'm thinking of these comments as catching TODOs so my thinking was to either 
- make the change in this PR 
- move into an issue 
- discuss and decide we're not doing it 

thanks!

2020-06-23 03:40 UTC, nickmeinhold commented on test/conversations_page_test.dart
> +    testWidgets('find conversationId, uids, displaynames and photoURLs',
The test description doesn't describe the test in a way I understand what it's doing - we don't have any documentation for the tests so I think it's important we have descriptions that describe the tests clearly so you can get what is being tested from the description.

2020-06-23 03:40 UTC, nickmeinhold commented on test/conversations_page_test.dart
> +    testWidgets('find conversationId, uids, displaynames and photoURLs',
I imagine you might be getting annoyed by these requests - I'm not meaning to be difficult I really do think this is worth bothering about as the tests are often the best way to figure out how parts of the code work and having a description that you can glance at and know what the test is doing makes the process of finding the relevant test so much easier. Please feel free to ask me to do anything, I'm not meaning to create an annoying burden.

2020-06-23 03:40 UTC, nickmeinhold commented on test/conversations_page_test.dart
> +    testWidgets('no exception when null displaynames',
imo this description is a bit clearer than the previous one but could be clearer too.

2020-06-23 03:40 UTC, nickmeinhold commented on test/unit/extensions/document_snapshot_extension_test.dart
> +        '.toMessage() will return valid DateTime when valid Timestamp in database',
> in database 

does toMessage return a DateTime? or a Message? 
is a valid Timestamp being in the database what matters? I would imagine there are ways the db could have a timestamp but produce an invalid document snapshot

2020-06-23 03:40 UTC, nickmeinhold commented on test/unit/extensions/document_snapshot_extension_test.dart
> +        '.toUserItem() will have empty displayName and photoURL if not populated',
I'm not clear what the test is testing

2020-06-23 03:40 UTC, nickmeinhold commented on test/unit/extensions/document_snapshot_extension_test.dart
> +  group('toUserItem()', () {
> If I wanted to have a group for the functions could we use the class.function() like group('DocumentSnapshot.toMessage()' ?

Yeah for sure

2020-06-23 03:48 UTC, nickmeinhold approved these changes
Sorry I think I might have jumped the gun - did you request another review? Something made me think you had but I think I may have gotten that wrong... sorry! 

IMO I thought there were two things to either add into this PR or move to an issue: 
- a function in ConversationItem that prints a truncated combine list 
- documentation (that being test descriptions & some explanations via comments in [eg.] the mock classes) 

I'm very happy to branch off your branch and have a go at these, or make issues or discuss further. 

Thanks for all your hard work and sorry if I jumped into another review before being asked!

2020-06-23 05:10 UTC, merged